name: workflow-orders-api
on:
  push:
    branches:
      - feature/*
jobs:
  application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - run: chmod +x gradlew
      - name: Test
        run: ./gradlew test --tests "*"