name: Orders API CI (Continuous Integration)

on:
  push:
    branches:
      - develop

jobs:
  build-application:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 22
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22'
          cache: 'gradle'
        run: chmod +x gradlew
      
      - name: Build application
        run: ./gradlew build

      - name: Test application
        run: ./gradlew test --tests "*"

  create-pull-request:
    needs: build-application
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create pull request
        run: gh pr create -B main -H develop --title 'Merge Develop into Main' --body 'Created automatic Pull Request by Github action.'
        env:
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}